# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_gender.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_gender_form(object):
    def setupUi(self, input_gender_form):
        input_gender_form.setObjectName("input_gender_form")
        input_gender_form.setWindowModality(QtCore.Qt.WindowModal)
        input_gender_form.resize(235, 122)
        input_gender_form.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label = QtWidgets.QLabel(input_gender_form)
        self.label.setGeometry(QtCore.QRect(20, 30, 191, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_female = QtWidgets.QPushButton(input_gender_form)
        self.btn_female.setGeometry(QtCore.QRect(140, 80, 75, 23))
        self.btn_female.setObjectName("btn_female")
        self.btn_male = QtWidgets.QPushButton(input_gender_form)
        self.btn_male.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.btn_male.setObjectName("btn_male")

        self.retranslateUi(input_gender_form)
        QtCore.QMetaObject.connectSlotsByName(input_gender_form)

    def retranslateUi(self, input_gender_form):
        _translate = QtCore.QCoreApplication.translate
        input_gender_form.setWindowTitle(_translate("input_gender_form", "Gender"))
        self.label.setText(_translate("input_gender_form", "Is the singer male or female?"))
        self.btn_female.setText(_translate("input_gender_form", "Female"))
        self.btn_male.setText(_translate("input_gender_form", "Male"))
