# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_filename.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class InputFilename_Dialog(object):
    def setupUi(self, input_text_form):
        input_text_form.setObjectName("input_text_form")
        input_text_form.setWindowModality(QtCore.Qt.WindowModal)
        input_text_form.resize(235, 122)
        input_text_form.setFocusPolicy(QtCore.Qt.StrongFocus)
        input_text_form.setWindowFlags(QtCore.Qt.FramelessWindowHint)  # Remove title bar and buttons
        self.filename = QtWidgets.QPlainTextEdit(input_text_form)
        self.filename.setGeometry(QtCore.QRect(10, 50, 211, 21))
        self.filename.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.filename.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.filename.setPlainText("")
        self.filename.setObjectName("filename")
        self.label = QtWidgets.QLabel(input_text_form)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.label.setObjectName("label")
        self.btn_enter = QtWidgets.QPushButton(input_text_form)
        self.btn_enter.setGeometry(QtCore.QRect(150, 90, 75, 23))
        self.btn_enter.setObjectName("btn_enter")
        self.btn_cancel = QtWidgets.QPushButton(input_text_form)
        self.btn_cancel.setGeometry(QtCore.QRect(60, 90, 75, 23))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(input_text_form)
        QtCore.QMetaObject.connectSlotsByName(input_text_form)

        # Connect buttons
        self.btn_enter.clicked.connect(self.enter_clicked)
        self.btn_cancel.clicked.connect(self.cancel_clicked)

        # Variables
        self.name = ''

    def retranslateUi(self, input_text_form):
        _translate = QtCore.QCoreApplication.translate
        input_text_form.setWindowTitle(_translate("input_text_form", "Enter Name"))
        self.label.setText(_translate("input_text_form", "Enter File Name"))
        self.btn_enter.setText(_translate("input_text_form", "Enter"))
        self.btn_cancel.setText(_translate("input_text_form", "Cancel"))
        
    def enter_clicked(self):
        self.name = self.filename.toPlainText()
        self.accept()
        
    
    def cancel_clicked(self):
        self.reject()
        pass