# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MacDsgn_Vocalizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.MainFrame.setMinimumSize(QtCore.QSize(1024, 720))
        self.MainFrame.setMaximumSize(QtCore.QSize(1280, 720))
        self.MainFrame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.MainFrame.setStyleSheet("QFrame{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.CmdFrame = QtWidgets.QFrame(self.MainFrame)
        self.CmdFrame.setGeometry(QtCore.QRect(0, -20, 280, 720))
        self.CmdFrame.setMinimumSize(QtCore.QSize(280, 720))
        self.CmdFrame.setMaximumSize(QtCore.QSize(280, 720))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.CmdFrame.setFont(font)
        self.CmdFrame.setStyleSheet("QFrame{\n"
"border: 1px;\n"
"background-color: rgb(106, 106, 106);}")
        self.CmdFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CmdFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CmdFrame.setObjectName("CmdFrame")
        self.label = QtWidgets.QLabel(self.CmdFrame)
        self.label.setGeometry(QtCore.QRect(20, 40, 40, 40))
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setStyleSheet("QLabel{\n"
"image: url(:/MainLogo/MainLogo.png);}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.CmdFrame)
        self.label_2.setGeometry(QtCore.QRect(80, 50, 175, 25))
        self.label_2.setMinimumSize(QtCore.QSize(175, 25))
        self.label_2.setMaximumSize(QtCore.QSize(175, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(226, 226, 226);}")
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(self.CmdFrame)
        self.scrollArea.setGeometry(QtCore.QRect(0, 130, 281, 331))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"background-color: rgb(106, 106, 106);\n"
"border: none;}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 331))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 261, 331))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(195, 195, 195);}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(260, 0, 20, 331))
        self.verticalScrollBar.setMinimumSize(QtCore.QSize(20, 0))
        self.verticalScrollBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalScrollBar.setStyleSheet("QScrollBar:vertical {\n"
"height: 20px;\n"
"width:5px;\n"
"color: rgb(106, 106, 106);\n"
"}")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.CmdFrame)
        self.pushButton.setGeometry(QtCore.QRect(20, 90, 230, 35))
        self.pushButton.setMinimumSize(QtCore.QSize(230, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(230, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-radius: 5px;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.CmdFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 520, 190, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(190, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(190, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 1px;\n"
"border-radius: 2px;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.CmdFrame)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 470, 230, 35))
        self.pushButton_6.setMinimumSize(QtCore.QSize(230, 35))
        self.pushButton_6.setMaximumSize(QtCore.QSize(230, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-radius: 5px;}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.CmdFrame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 640, 190, 32))
        self.pushButton_3.setMinimumSize(QtCore.QSize(190, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(190, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 1px;\n"
"border-radius: 2px;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.CmdFrame)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 600, 190, 32))
        self.pushButton_4.setMinimumSize(QtCore.QSize(190, 32))
        self.pushButton_4.setMaximumSize(QtCore.QSize(190, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 1px;\n"
"border-radius: 2px;}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.CmdFrame)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 560, 190, 32))
        self.pushButton_5.setMinimumSize(QtCore.QSize(190, 32))
        self.pushButton_5.setMaximumSize(QtCore.QSize(190, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(195, 195, 195);\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 1px;\n"
"border-radius: 2px;}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.MainFrame)
        self.label_3.setGeometry(QtCore.QRect(620, 50, 300, 300))
        self.label_3.setMinimumSize(QtCore.QSize(300, 300))
        self.label_3.setStyleSheet("QLabel{\n"
"image: url(:/MainLogo/MainLogo.png);}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "VOCALIZER"))
        self.pushButton.setText(_translate("MainWindow", "Categorize Voice"))
        self.pushButton_2.setText(_translate("MainWindow", "Soprano"))
        self.pushButton_6.setText(_translate("MainWindow", "Train Voice"))
        self.pushButton_3.setText(_translate("MainWindow", "Bass"))
        self.pushButton_4.setText(_translate("MainWindow", "Tenor"))
        self.pushButton_5.setText(_translate("MainWindow", "Alto"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
